services:
  family-e-ink-dashboard:
    image: ghcr.io/stefanthoss/family-e-ink-dashboard:latest
    container_name: family-e-ink-dashboard
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - OWM_API_KEY=
      - ICS_URL=
      - DISPLAY_TZ=
      - LAT=
      - LNG=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
